### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Varun-Sethi-Dev** [Chaintech-Network/ComposeMultiplatformMediaPlayer#12]
Can You add a parameter for playing the video muted or unmuted so that the user can 1st watch the video muted and if required then unmute it.
Or just provide the source code for the library whose only jar or compiled code is available but not editable or i do not know how to do it.

**Comment by ctn-mobile-innovation** [comment]
@Varun-Sethi-Dev Good Suggestion! we will add in upcoming version and let you know!

**Comment by ctn-mobile-innovation** [comment]
@Varun-Sethi-Dev it's added Please check updated Read.me for usage details
