### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by jQrgen** [Chaintech-Network/ComposeMultiplatformMediaPlayer#14]
Where is the source code for the library used in the examples? Such as `chaintech.videoplayer.ui.audio`

**Comment by ctn-mobile-innovation** [comment]
@jQrgen you can checkout  implementation("network.chaintech:compose-multiplatform-media-player:1.0.19")

**Comment by DatL4g** [comment]
> [!Warning]
> Using this (or any other mentioned) library is still up to you, however keep in mind that you will be responsible if any of them **harms users** and the **Play Store or App Store will take actions against you**, not the library owner.

All projects of this organization(?) seem fishy and I highly recommed to **NOT USE IT**.

Other "libraries" with no source code are:
- https://github.com/Chaintech-Network/ComposeMultiplatformScreenCapture
- https://github.com/Chaintech-Network/QRKitComposeMultiplatform
- https://github.com/Chaintech-Network/CMPCharts
- https://github.com/Chaintech-Network/CMP-image-pick-n-crop
- https://github.com/Chaintech-Network/sdp-ssp-compose-multiplatform
- https://github.com/Chaintech-Network/CMPShakeDetection
- https://github.com/Chaintech-Network/CMPCountryCodePicker
- https://github.com/Chaintech-Network/CMPToast
- https://github.com/Chaintech-Network/CMPEasyPermission
- https://github.com/Chaintech-Network/CMPConnectivityMonitor
- https://github.com/Chaintech-Network/CMP_tooltip

Some of them require "dangerous" permissions which are in fact necessary for there functionality but as long as we don't know how they're handled we can't ensure safe usage.

**Comment by vipulyaara** [comment]
Would it be possible to open source the implementation so others can extend and contribute?

**Comment by ctn-mobile-innovation** [comment]
@vipulyaara we are planning to form a community where members can contribute, will share details soon.

**Comment by yuroyami** [comment]
@ctn-mobile-innovation Users can contribute here ON GITHUB. There is no such thing as "community where members can contribute" if GitHub does the job pretty fine.

**Comment by StefanOltmann** [comment]
If you're looking for a real CMP video library check out https://github.com/kdroidFilter/Compose-Media-Player
