### ISSUE TITLE
Audio: What formats are supported?

### ISSUE THREAD

**Issue by jQrgen** [Chaintech-Network/ComposeMultiplatformMediaPlayer#16]
I'm working on an app that needs: .mp3, .ogg, .aac, .aiff, .wma, .flac, .alac and .wav support

**Comment by ctn-mobile-innovation** [comment]
@jQrgen Almost all formats are supported, if you face issue with any specific format let us know!

**Comment by ctn-mobile-innovation** [comment]
@jQrgen Please check updated Readm.me file we have added table for this information!

**Comment by jQrgen** [comment]
Thanks @ctn-mobile-innovation
