### ISSUE TITLE
Crash java.lang.NoSuchMethodError: No static method VerticalPager

### ISSUE THREAD

**Issue by Ant1kguild** [Chaintech-Network/ComposeMultiplatformMediaPlayer#18]
`java.lang.NoSuchMethodError: No static method VerticalPager-xYaah8o(Landroidx/compose/foundation/pager/PagerState;Landroidx/compose/ui/Modifier;Landroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/foundation/pager/PageSize;IFLandroidx/compose/ui/Alignment$Horizontal;Landroidx/compose/foundation/gestures/snapping/SnapFlingBehavior;ZZLkotlin/jvm/functions/Function1;Landroidx/compose/ui/input/nestedscroll/NestedScrollConnection;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/foundation/pager/PagerKt; or its super classes (declaration of 'androidx.compose.foundation.pager.PagerKt' appears in /data/app/~~uwu2u6F-rfUxI25YZhFSig==/com.mico.stylish.lock.application.android-KXs2W5DW6jNdAhkudCmuxA==/base.apk)`

`kotlinVer = "2.0.0"`
`jetbrainsComposeVer = "1.6.11"`

**Comment by ctn-mobile-innovation** [comment]
@Ant1kguild Please check in latest version of Library!
