### ISSUE TITLE
Are there any plans to support web? (js)

### ISSUE THREAD

**Issue by slickorange** [Chaintech-Network/ComposeMultiplatformMediaPlayer#23]
There is really a huge need for this in the KMP ecosystem

**Comment by ctn-mobile-innovation** [comment]
@slickorange Yes it's in roadmap, Please refer ReadMe section

**Comment by slickorange** [comment]
@ctn-mobile-innovation Thanks, I did but the roadmap refers only to Desktop Support and I did not see anything about js

**Comment by jaredsburrows** [comment]
https://github.com/Chaintech-Network/ComposeMultiplatformMediaPlayer/issues/2
