### ISSUE TITLE
Cannot access class 'org.jetbrains.compose.resources.DrawableResource'

### ISSUE THREAD

**Issue by Ahmedbadr22** [Chaintech-Network/ComposeMultiplatformMediaPlayer#26]
![image](https://github.com/user-attachments/assets/ecd0309d-930e-424a-a4dc-a77064e83dfc)

**Comment by ctn-mobile-innovation** [comment]
@Ahmedbadr22 Can you please share compose version which you are using?

**Comment by ctn-mobile-innovation** [comment]
Since no reply on this, we assume it's fixed so closing this issue!
