### ISSUE TITLE
About Desktop support for ComposeMultiplatformMediaPlayer  ? Use VLC ?

### ISSUE THREAD

**Issue by CMingTseng** [Chaintech-Network/ComposeMultiplatformMediaPlayer#28]
I suggest if vlc can be used universally?

Use on Android

Exoplayer_VLC (may need to be modified and improved, but it can be submitted later so that Exoplayer can officially support it - for example, Exoplayer previously supported FFMPEG)
(https://github.com/tyazid/Exoplayer_VLC)

Then the Desktop side follows this example Kashif-E
/
Compose-Multiplatform-Video-Player (https://github.com/Kashif-E/Compose-Multiplatform-Video-Player/blob/a9c00c7b6e7f4683eda27d0cc3cd3df3ff79c09d/common/build.gradle.kts#L76) uses vlc directly

https://github.com/caprica/vlcj

https://blog.csdn.net/wangkai13810651628/article/details/124007319

https://github.com/timo-drick/cfd_video/tree/main

Then there are many examples of direct VLC (which can support more playback formats) on iOS.

This is my idea

THX

**Comment by ctn-mobile-innovation** [comment]
@CMingTseng That's good suggestion we will explore it for sure, and get back to you!

**Comment by ctn-mobile-innovation** [comment]
@CMingTseng we have explored possibility of VLC in every platform but as per initial testing it was not performing as great as current library, also we have desktop support now, so in future we might explore this option again.

But thanks again for suggestion!
