### ISSUE TITLE
Modifier.fillMaxWidth() not working inside HorizontalPager

### ISSUE THREAD

**Issue by kotlin-compose-multiplatform** [Chaintech-Network/ComposeMultiplatformMediaPlayer#29]
When I add VideoPlayer component inside HorizontalPager second Item, width contains first item and third item not only second item. I wrap VideoPlayer component with Box, but not worked. Please test VideoPlayer component with HorizontalPager it has issue. Please fix this issue.

**Comment by ctn-mobile-innovation** [comment]
@kotlin-compose-multiplatform  Thanks for reporting! let us check and get back to you

**Comment by kotlin-compose-multiplatform** [comment]
I found solution for this problem, make please screenSize default value FIT and give screenSize parameter for VideoPlayerView for customize screenSize value! @ctn-mobile-innovation

**Comment by ctn-mobile-innovation** [comment]
@kotlin-compose-multiplatform It's added in latest update, you can refer "videoFitMode" in read me.
