### ISSUE TITLE
Drawable Resource Error

### ISSUE THREAD

**Issue by Ansalpandey** [Chaintech-Network/ComposeMultiplatformMediaPlayer#32]
Cannot access class 'org. jetbrains. compose. resources. DrawableResource'. Check your module classpath for missing or conflicting dependencies

I am getting this error while Accessing PlayerConfig() in Jetpack Compose App. How to resolve it?

**Comment by ctn-mobile-innovation** [comment]
@Ansalpandey can you help us with compose version on your project?

**Comment by Ansalpandey** [comment]
> @Ansalpandey can you help us with compose version on your project?

Here's my libs.versions.toml file

[versions]
agp = "8.7.1"
kotlin = "2.0.20"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.6"
activityCompose = "1.9.3"
composeBom = "2024.10.00"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

**Comment by ctn-mobile-innovation** [comment]
@Ansalpandey You are using it into KMP/CMP or Android?

**Comment by Ansalpandey** [comment]
> @Ansalpandey You are using it into KMP/CMP or Android?

No I am using it in Jetpack Compose.

**Comment by ctn-mobile-innovation** [comment]
@Ansalpandey Please check with latest version!
