### ISSUE TITLE
Can't see control bar after it's hidden when modifier size is small

### ISSUE THREAD

**Issue by fluxxion82** [Chaintech-Network/ComposeMultiplatformMediaPlayer#40]
I've got a composable than contains the video player.
```
FooMediaItem(
    mediaUrl = item.second.imagePath,
    modifier = Modifier
        .size(125.dp)
        .clip(RoundedCornerShape(8.dp)),
)
``` 
I use this composable in a few places in my app, and I pass different modifiers to it. when the video is first loaded, I see the controls. I have `controlHideIntervalSeconds` set to 5, and after the 5 seconds, the controls are hidden as expected. The issue is that I can't bring the controls back into view after this interval when the size is 125 dp (not a hard limit) or less. because of issue https://github.com/Chaintech-Network/ComposeMultiplatformMediaPlayer/issues/30, I'm setting a height on the modifier in one place and when it's like 400 dp, I see the control coming back into view as expected. it seems just when the height or size is small enough, the controls don't come back into view. This is happening on Android and iOS.

**Comment by fluxxion82** [comment]
@ctn-mobile-innovation I feel like there's some weird modifier stuff going on. The Modifier that is being passed to `VideoPlayerWithControl` is given to the main Box composable _and_ ` CMPPlayer`. I think `CMPPlayer` should have it's own modifier, probably `Modifier.fillMaxSize()`. I think if you do that it will fix this issue and #30

**Comment by fluxxion82** [comment]
Another issue I'm seeing is that if I set `isMute` to true, I can't seem to unmute the video. If you initialize the `isMute` mutable state with the player config, I think maybe that will help: `var isMute by remember { mutableStateOf(playerConfig.isMute ?: false) }` instead of initializing `isMute` with false and then setting it with `playerConfig.isMute?.let { isMute = it }` afterwards.

**Comment by ctn-mobile-innovation** [comment]
@fluxxion82 Thanks for reporting issue! we had fixed in latest version, Please check and let us know!
