### ISSUE TITLE
Component names do not follow the Compose convention

### ISSUE THREAD

**Issue by JacobCube** [Chaintech-Network/ComposeMultiplatformMediaPlayer#41]
Hey, I've noticed you're using the "View" naming convention within your component names.

This is incorrect under the [Compose Api ](https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md) convention, so I propose the name would change to anything BUT name containing "View".

**Comment by ctn-mobile-innovation** [comment]
Good Suggestion! we had improved naming in latest version! will improve more over the time!
