### ISSUE TITLE
 How to Customize the Player’s Custom UI

### ISSUE THREAD

**Issue by Arun1811** [Chaintech-Network/ComposeMultiplatformMediaPlayer#44]
I am facing an issue while trying to customize the UI for the player. The error message says:
Cannot access 'CMPAudioPlayer': it is internal in 'chaintech.videoplayer.util'.

It seems the CMPAudioPlayer class is not accessible due to its internal modifier. Could you please guide me on how to resolve this issue and enable UI customization for the player?

**Comment by ctn-mobile-innovation** [comment]
To access audio player you can use "AudioPlayerComposable" also you can do some customisation which can be availd by using audioPlayerConfig.
 
if you want more customise UI Please share in detail so we can review it!
