### ISSUE TITLE
Support other urls

### ISSUE THREAD

**Issue by Micoder-dev** [Chaintech-Network/ComposeMultiplatformMediaPlayer#6]
It doesn't work with any live URLS like `m3u8` etc...

**Comment by ctn-mobile-innovation** [comment]
Yes, currently it's not supported but once we done with Desktop support we will work on this!

**Comment by herveweb** [comment]
Does this support playing videos from local resources? And if so, how? (What should be the url format)

**Comment by ctn-mobile-innovation** [comment]
@herveweb It's in our roadmap! we will add and let you know!

**Comment by ctn-mobile-innovation** [comment]
@Micoder-dev Can you send us sample url of format which you requesting as we are planning to work on same!

**Comment by ctn-mobile-innovation** [comment]
@Micoder-dev @herveweb It's added in latest version!
