### ISSUE TITLE
Cannot access class 'org.jetbrains.compose.resources.DrawableResource'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by bkmalkoc** [Chaintech-Network/ComposeMultiplatformMediaPlayer#8]
Cannot access class 'org.jetbrains.compose.resources.DrawableResource'. Check your module classpath for missing or conflicting dependencies

when implementing AudioPlayerConfig() inside the AudioPlayerView(), having this error. 

`AudioPlayerView(
        modifier = modifier.wrapContentHeight(),
        audios = listOf(
            AudioFile(
                audioUrl = state.url,
                audioTitle = "",
                thumbnailUrl = ""
            )
        ),
        audioPlayerConfig = AudioPlayerConfig()
    )`

**Comment by ctn-mobile-innovation** [comment]
@bkmalkoc can you provide us more detail like which compose multiplatform & KMP version you are using

**Comment by ctn-mobile-innovation** [comment]
@bkmalkoc Please check in latest version and let us know!
